### ISSUE TITLE
Not done at all

### ISSUE THREAD

**Issue by refdoc** [jonBitgood/Transcription-Blackfoot-Matthew#1]
Hi, this is not yet USFM text, though you clearly aimed at the right thing. But so far you have only tagged the chapter markers and a couple of others. 

None of the verses have been tagged appropriately. I do not know Blackfoot, but I am wondering if the captiised bits are titles - if so they should be tagged too.

**Comment by jonbitgood** [comment]
Thanks refdoc! We did indeed need to update the SFM, all verses are now appropriately tagged.

The capitalized bits are not titles but rather a stylistic drop-cap element left over from the original printing.
