### ISSUE TITLE
License not appropriate

### ISSUE THREAD

**Issue by refdoc** [jonBitgood/Transcription-Blackfoot-Matthew#2]
This text is from 1890, so to add a license to it when the text is in the public domain is probably not appropriate. The effort of proofreading, while laudable is not copyrightable, the mark up is so limited as to not to have much or any copyrightable value.

**Comment by jonbitgood** [comment]
I agree wholeheartedly, I don't believe the license to hold any validity and would never take any action against any organization who treated it like a public domain bible. It is however, highly effective at countering copy fraud. In 2016, the British and Foreign Bible Society claimed an "all rights reserved" copyright on the Danezaa Bible (from 1886!) that I had transcribed. If you know of a different way to prevent copy fraud, I'd be interested to hear it.

**Comment by refdoc** [comment]
I think answering a wrong with a wrong is not really getting anyone anywhere. In essence this is copyfraud too, only of course much more generous one. Personally I think a strong letter to tthe BFBS will be more productive than claiming a copyright which will not hold water and damage your reputation

**Comment by refdoc** [comment]
Right now this stops me to produce a CrossWire module from it.

**Comment by jonbitgood** [comment]
I did write a few dozen emails or so.

I know CrossWire has both Creative Commons Text and [Fully copyrighted texts](http://crosswire.org/sword/modules/ModInfo.jsp?modName=MonKJV) with permissions so there should be no barrier to entry there. If you're worried about the integrity of the meta data please just put Public Domain on your Cross wire conversion.
